### PR TITLE
Support null safety

### PR DESCRIPTION
**Pull request by mvrsn**

### CODE REVIEW

**Comment by esarbanis** [comment]
Oh, wow thanks @mvrsn ! 

If you can fix the conflict I created earlier 😅  and squash your commits, I will be happy to merge it for v.0.3.0 which is going to be the null-safe version.

**Comment by mvrsn** [comment]
@esarbanis sure, will do 🙂

**Comment by mvrsn** [comment]
@esarbanis ✅

**Comment by esarbanis** [comment]
@mvrsn nice! I will merge it as soon as I find the time to sort out the versions.

Thanks again!

**Comment by esarbanis** [comment]
Closes #9

**Comment by isorensen** [comment]
Dear @esarbanis , any update on when it will be published to pub.dev ?
Thanks a lot for the effort!

**Comment by esarbanis** [comment]
Null safety landed on v0.3.0

**Pull request merged**
